[package]
name = "moray"
version = "0.1.0"
authors = ["Rui Loura <rui@joyent.com>"]
edition = "2018"

[dependencies]
rust_fast = { git = "https://github.com/joyent/rust-fast" }
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
uuid = {version = "0.7.4", features = ["v4"] }

[dev-dependencies]
quickcheck = "0.8.0"
rand = "0.6.4"

